PRODUCT_VERSION_MAJOR = 15
PRODUCT_VERSION_MINOR = 0

LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)

LINEAGE_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)$(LINEAGE_EXTRAVERSION)-$(LINEAGE_BUILD)

# Internal version
LINEAGE_VERSION := $(LINEAGE_BUILD)-ota-$(BUILD_ID).$(LINEAGE_BUILD_DATE)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINE-AGE_VERSION_SUFFIX)

# LineageOS version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.lineage.version=$(LINEAGE_VERSION) \
    ro.lineage.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.lineage.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.lineage.releasetype=$(LINEAGE_BUILDTYPE) \
    ro.modversion=$(LINEAGE_VERSION)
